version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11

    working_directory: ~/repo

    steps:
      - checkout

      - run: yarn install

      - run: yarn build

      - deploy:
          name: Deploy to Now
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              yarn run deploy:dev
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn run deploy:prod
            else
              GIT_HASH=$(git rev-parse --short HEAD)
              SANITIZED_BRANCH=$(tr "/" "-" <<<$CIRCLE_BRANCH)
              BUILD_URL=$(npx now --name mybit.io build -t $NOW_DEVELOPMENT_TOKEN --public)
              npx now alias ${BUILD_URL} \
              ${GIT_HASH}-mybit-io-dev -t \
              $NOW_DEVELOPMENT_TOKEN
              npx now alias ${BUILD_URL} \
              ${SANITIZED_BRANCH}-mybit-io-dev -t \
              $NOW_DEVELOPMENT_TOKEN
            fi
